name: mooTree
author: abidibo
category: Utilities
tags: [tree, expand, collapse, navigation, menu, folder, archive]
docs: http://www.abidibo.net/projects/js/mooTree
demo: http://www.abidibo.net/projects/js/mooTree/demo
current: 0.1
